
Vagrant.configure("2") do |config|
  # Enable Vagrant Hostmanager plugin to automatically manage /etc/hosts entries
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
  ### Database VM (db01) ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"  # Base image (CentOS Stream 9)
    db01.vm.box_version = "9.0.43"  # Specific version of the box
    # db01.vm.box_version = "0"
    db01.vm.hostname = "db01"  # Hostname of the VM
    db01.vm.network "private_network", ip: "192.168.56.15"  # Private network with static IP
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"  # Allocate 600MB of RAM
    end
  end
  
  ### Memcached VM (mc01) #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.box_version = "9.0.43"
    # mc01.vm.box_version = "0"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
  end
  
  ### RabbitMQ VM (rmq01) ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.box_version = "9.0.43"
    # rmq01.vm.box_version = "0"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.13"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
  end
  
  ### Tomcat Application Server VM (app01) ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    # app01.vm.box = "ubuntu/jammy64"  # Use Ubuntu 22.04 (Jammy Jellyfish)
    app01.vm.box_version = "9.0.43"
    # app01.vm.box_version = "0"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "750"  # Higher memory allocation for Tomcat
    end
  end
   
  ### Nginx Web Server VM (web01) ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"  # Use Ubuntu 22.04 (Jammy Jellyfish)
    # web01.vm.box_version = "0"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.gui = true  # Enable GUI mode for this VM (useful for debugging UI-related tasks)
      vb.memory = "800"
    end
  end

end
