
# Defining the Vagrant Configuration format version
Vagrant.configure("2") do |config|
  # Enable Vagrant Hostmanager plugin to automatically manage /etc/hosts entries
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
    
  ### Database VM (db01) ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "generic/centos9s"
    db01.vm.box_version = "4.3.12"
    # db01.vm.box = "eurolinux-vagrant/centos-stream-9"  # Base image (CentOS Stream 9)
    # db01.vm.box_version = "9.0.48"  # Specific version of the box
    # db01.vm.box = "centos9_kernel573_hosa"  # My own image
    db01.vm.hostname = "db01"  # Hostname of the VM
    db01.vm.network "private_network", ip: "192.168.56.15"  # Private network with static IP
    
    # Configuring the provider settings for VirtualBox
    db01.vm.provider "virtualbox" do |vb|
      vb.gui = false    # Run the VM without GUI
      vb.memory = "600"  # Allocate 600MB of RAM
    end

    # Run external script on VM for provisioning
    db01.vm.provision "shell", path: "provisioning/db01-script.sh", privileged: false

    db01.vm.synced_folder ".", "/vagrant/" 

  end
  

  ### Memcached VM (mc01) #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "generic/centos9s"
    mc01.vm.box_version = "4.3.12"
    # mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    # mc01.vm.box_version = "9.0.48"
    # mc01.vm.box = "centos9_kernel573_hosa"  # My own image
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end

    # Run external script on VM for provisioning
    mc01.vm.provision "shell", path: "provisioning/mc01-script.sh"
    
  end
  
  ### RabbitMQ VM (rmq01) ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "generic/centos9s"
    rmq01.vm.box_version = "4.3.12"
    # rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    # rmq01.vm.box_version = "9.0.48"
    # rmq01.vm.box = "centos9_kernel573_hosa"  # My own image
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.13"
    
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
    
    # Run external script on VM for provisioning
    rmq01.vm.provision "shell", path: "provisioning/rmq01-script.sh"

  end
  
  ### Tomcat Application Server VM (app01) ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "ubuntu/jammy64"  # Use Ubuntu 22.04 (Jammy Jellyfish)
    # app01.vm.box = "ubuntu_24.04_hosa"  # Use Ubuntu 22.04 (Jammy Jellyfish)
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "750"  # Higher memory allocation for Tomcat
    end

    # Run external script on VM for provisioning
    app01.vm.provision "shell", path: "provisioning/app01-script.sh"
  
  end

  ### Nginx Web Server VM (web01) ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"  # Use Ubuntu 22.04 (Jammy Jellyfish)
    # web01.vm.box = "ubuntu_24.04_hosa"  # Use Ubuntu 22.04 (Jammy Jellyfish)
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    
    web01.vm.provider "virtualbox" do |vb|
      vb.gui = true  # Enable GUI mode for this VM (useful for debugging UI-related tasks)
      vb.memory = "850"
    end
    
    # Run external script on VM for provisioning
    web01.vm.provision "shell", path: "provisioning/web01-script.sh"
  
  end
end




















# For the db01
# vb.customize [
#   "storageattach", :id, 
#   "--storagectl", "IDE Controller",
#   "--port", 1,
#   "--device", 0, 
#   "--type", "dvddrive", 
#   "--medium", "emptydrive"]

# db01.vm.synced_folder "logs", "/vagrant/logs", 
#   create: true, 
#   owner: "vagrant", 
#   group: "vagrant", 
#   mount_options: [
#     "dmode=775", 
#     "fmode=664"
#   ]